# https://docs.travis-ci.com/user/reference/osx/
language: c
os: osx
script: make travis
matrix:
  include:
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode7.3
